/*
 * The following program is used to generate the constants for
 * computing sched averages.
 *
 * ==============================================================
 *		C program (compile with -lm)
 * ==============================================================
 */

#include <math.h>
#include <stdio.h>

#define SHIFT 32

void calc_runnable_avg_yN_inv(int halflife, double y, const char *name)
{
	int i;
	unsigned int x;

	printf("static const u32 %s[] __maybe_unused = {", name);
	for (i = 0; i < halflife; i++) {
		x = ((1UL<<32)-1)*pow(y, i);

		if (i % 6 == 0) printf("\n\t");
		printf("0x%8x, ", x);
	}
	printf("\n};\n\n");
}

void calc_converged_max(int halflife, double y,
			const char *period_name, const char *max_name)
{
	int n = -1;
	long last = 0, max = 1024;
	long y_inv = ((1UL<<32)-1)*y;

	for (; ; n++) {
		if (n > -1)
			max = ((max*y_inv)>>SHIFT) + 1024;
			/*
			 * This is the same as:
			 * max = max*y + 1024;
			 */

		if (last == max)
			break;

		last = max;
	}
	n--;
	printf("#define %s %d\n", period_name, halflife);
	printf("#define %s %ld\n", max_name, max);
//	printf("#define LOAD_AVG_MAX_N %d\n\n", n);
}

void main(void)
{
	double y16, y8;

	printf("/* Generated by Documentation/scheduler/sched-pelt; do not modify. */\n\n");

	y16 = pow(0.5, 1/16.0);
	calc_runnable_avg_yN_inv(16, y16, "runnable_avg_yN_inv");
	calc_converged_max(16, y16, "LOAD_AVG_PERIOD", "LOAD_AVG_MAX");

	y8 = pow(0.5, 1/8.0);
	calc_runnable_avg_yN_inv(8, y8, "runnable_avg_yN_inv_fast");
	calc_converged_max(8, y8, "LOAD_AVG_PERIOD_FAST", "LOAD_AVG_MAX_FAST");
}
